<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.Employer.Aan.Domain\SFA.DAS.Employer.Aan.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SFA.DAS.Aan.SharedUi" Version="0.1.114" />
    <PackageReference Include="SFA.DAS.GovUK.Auth" Version="17.1.190" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

</Project>
